Bag/tl 021 activity controller exceptions
sidgrouse/LetsDoStuff pull request #17
Opened 2020-12-15 14:34 UTC by TarasovAA

2020-12-15 18:56 UTC, OnofreichukRoman commented on LetsDoStuff.WebApi/Controllers/ActivityController.cs
> -
If you return only list of activities you should delete the `ActionResult<>`

2020-12-15 18:58 UTC, OnofreichukRoman requested changes

2020-12-15 18:58 UTC, OnofreichukRoman commented on LetsDoStuff.WebApi/Controllers/ActivityController.cs
>              return activities;
If you return only list of activities you should delete the ActionResult<>

2020-12-15 21:41 UTC, OnofreichukRoman submitted a review, later dismissed

2020-12-16 06:38 UTC, sidgrouse approved these changes

2020-12-16 06:39 UTC, merged